FROM ubuntu:22.04

RUN mkdir /code
WORKDIR /code

ENV PYTHONUNBUFFERED 1

RUN apt-get -y update --fix-missing 
RUN apt-get -y install curl unzip wget

# Git
RUN apt-get -y install git

# Python
RUN apt-get -y install python3 python3-pip 
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install Python requirements
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt