from typing import List

from jinja2 import Environment, FileSystemLoader


def generate_prompts_from_text_list(texts: List[str], template_path: str, prompt_file_name: str) -> List[str]:
    """
    Generate a list of prompts by filling in text from a list of strings into a Jinja2 template.

    Args:
        texts (List[str]): A list of strings containing the text.
        template_path (str): The path to the directory containing the Jinja2 template file.
        prompt_file_name (str): The name of the Jinja2 template file to be used for generating prompts.

    Returns:
        List[str]: A list of prompts generated by filling in the text into the template.
    """
    environment = Environment(loader=FileSystemLoader(template_path))
    template = environment.get_template(prompt_file_name)

    prompts = []
    for text in texts:
        prompt = template.render(text=text)
        prompts.append(prompt)

    return prompts
